[package]
name = "drungy_selfie"
version = "0.1.0"
edition = "2021"

[dependencies]

opencv = "0.71.0"
rand = "0.7.0"
regex="1.7.1"


[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
strip = true
lto = true
